# 7a Machine Learning - Part I

In this part of the exercise you will take a processed DataFrame containing all provided spectral data, divide it into training and test subsets, and use these to set up and test a k-nearest neighbours machine learning model.
<br>
<br>Once trained, this model should be able to classify unknown substitution patterns based on the labelled spectral data it has been presented with.

---

**Note:** Running this code will prevent some irrelevant errors popping up later on in the exercise.

In [12]:
import warnings
warnings.filterwarnings("ignore")

---

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import mpl_toolkits.mplot3d.axes3d as p3
%matplotlib inline
import C317
import os
os.scandir("/content/drive/MyDrive/Raw_IR_Spectra")
import sklearn.decomposition

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
import importlib
importlib.reload(C317)

a = C317.load_spectra(20)
a.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
    o-salicylaldehyde_4.txt  o-1-chloro-2-nitrobenzene_3.txt  \
0                 -0.000849                        -0.000447
1                 -0.000827                        -0.000170
2                  0.000180                        -0.000037
3                 -0.000098                         0.000216
4                  0.000221                         0.000097
5                  0.000331                        -0.000463
6                 -0.000040                        -0.000401
7                 -0.000173                        -0.000320
8                  0.000206                         0.000248
9                  0.000183                        -0.000332
10                 0.000043                        -0.000127
11                -0.000053                         0.000103
12                 0.000097                         0.000150
13                -0.000143                         0.000010
14                -0.000007                         0.000118
15                -0.000079                         0.000116
16                -0.000077                         0.000003
17                -0.000089                         0.000032
18                 0.000014                        -0.000042
19                 0.000065                         0.000115

    o-salicylic acid_4.txt  o-guaiacol_3.txt  o-aminobenzylalcohol_3.txt  \
0                -0.000650          0.000264                   -0.001211
1                -0.000150         -0.000794                   -0.000081
2                 0.000207         -0.000320                   -0.000219
3                -0.000342          0.000238                    0.000103
4                 0.000236         -0.000048                   -0.000125
5                 0.000031         -0.000004                   -0.000163
6                 0.000258         -0.000064                    0.000030
7                 0.000061          0.000008                    0.000035
8                -0.000035         -0.000012                   -0.000038
9                -0.000028          0.000105                    0.000088
10               -0.000068          0.000033                   -0.000050
11                0.000092          0.000008                    0.000001
12               -0.000135         -0.000066                    0.000035
13               -0.000145          0.000010                    0.000004
14                0.000064          0.000033                   -0.000019
15                0.000163          0.000038                   -0.000033
16               -0.000006         -0.000026                    0.000013
17               -0.000018         -0.000034                    0.000021
18                0.000005         -0.000014                   -0.000023
19                0.000082         -0.000016                   -0.000059

    m-tolualdehyde_3.txt  o-bromotoluene_3.txt  m-toluoyl chloride_3.txt  \
0               0.000308              0.000714                 -0.000275
1              -0.000210             -0.000715                  0.000114
2               0.000486             -0.000010                  0.000717
3              -0.000157              0.000337                 -0.000320
4              -0.000137              0.000018                 -0.000256
5              -0.000133              0.000021                  0.000533
6              -0.000230              0.000148                 -0.000209
7               0.000349              0.000218                  0.000003
8               0.000094             -0.000104                 -0.000289
9               0.000014              0.000016                  0.000123
10              0.000044             -0.000003                 -0.000088
11              0.000201              0.000129                 -0.000173
12              0.000008              0.000149                  0.000393
13             -0.000074             -0.000081                 -0.000052
14              0.000052             -0.000002                  0.000002
15              0.000019             -0.000055                  0.000106
16             -0.000020              0.000036                  0.000171
17              0.000106              0.000064                 -0.000027
18             -0.000073             -0.000062                  0.000016
19              0.000115              0.000014                  0.000068

    p-acetoxybenzoic_2.txt  m-aminoacetophenone_1.txt  ...  \
0                -0.000250              -3.125144e-04  ...
1                 0.000321               1.389693e-04  ...
2                -0.000047               2.490830e-04  ...
3                -0.000260              -2.591943e-04  ...
4                 0.000085              -7.754741e-06  ...
5                -0.000101              -2.700181e-04  ...
6                 0.000445               2.456666e-05  ...
7                -0.000071               8.115776e-05  ...
8                -0.000127               1.512035e-04  ...
9                 0.000064              -5.290091e-05  ...
10               -0.000060               1.467278e-06  ...
11               -0.000117              -6.624794e-05  ...
12                0.000020              -4.823474e-05  ...
13               -0.000023              -1.288377e-04  ...
14                0.000090               7.450132e-05  ...
15                0.000197              -8.007511e-05  ...
16               -0.000018              -8.735301e-05  ...
17               -0.000089               8.429005e-05  ...
18                0.000034               9.126164e-07  ...
19               -0.000048              -1.133323e-04  ...

    p-(trifluoromethyl)benzaldehyde_2.txt  p-aminophenol_4.txt  \
0                                0.000787         3.421660e-04
1                                0.000344         1.174880e-04
2                               -0.000547        -5.866038e-05
3                               -0.000152         1.351596e-04
4                                0.000245        -3.358443e-06
5                                0.000033         3.224318e-06
6                               -0.000080         1.999217e-04
7                                0.000022         4.054251e-05
8                               -0.000153         1.197266e-04
9                                0.000004        -6.930083e-05
10                               0.000148        -5.373276e-05
11                              -0.000148         1.139648e-05
12                              -0.000075        -5.038029e-08
13                              -0.000051        -7.700107e-06
14                               0.000083        -6.085557e-06
15                               0.000104         3.166323e-06
16                              -0.000008        -3.611261e-05
17                               0.000065         3.420785e-05
18                               0.000062        -2.253766e-05
19                               0.000046        -4.515064e-05

    p-hydroxybenzoic acid_1.txt  p-tolualdehyde_4.txt  p-iodoanisole_2.txt  \
0                 -3.732225e-04              0.000777            -0.000086
1                  3.847578e-04              0.000289             0.000529
2                 -3.141540e-04             -0.000142            -0.000110
3                 -3.456790e-04             -0.000127             0.000107
4                  8.552972e-07             -0.000354            -0.000310
5                 -1.375584e-04              0.000327             0.000004
6                 -9.350100e-05              0.000105             0.000005
7                 -4.129683e-06             -0.000166             0.000034
8                 -1.303063e-04             -0.000158            -0.000020
9                 -2.507342e-04             -0.000216             0.000044
10                -1.408311e-04             -0.000200             0.000009
11                 1.257542e-05              0.000138             0.000047
12                 2.532603e-04             -0.000152            -0.000002
13                 8.435605e-05              0.000030            -0.000082
14                -9.274859e-05              0.000083             0.000142
15                 1.008913e-05             -0.000101            -0.000049
16                 8.983981e-05             -0.000092             0.000051
17                -3.267305e-05             -0.000077            -0.000022
18                 1.071078e-04              0.000055             0.000101
19                 3.097808e-05              0.000071             0.000006

    p-iodoanisole_4.txt  p-iodophenol_4.txt  \
0             -0.000152           -0.000282
1              0.000595            0.000385
2             -0.000137            0.000124
3              0.000123            0.000229
4             -0.000374           -0.000143
5              0.000018            0.000304
6             -0.000017            0.000015
7              0.000047            0.000181
8             -0.000039            0.000181
9              0.000068           -0.000174
10             0.000012           -0.000071
11             0.000057            0.000021
12            -0.000009           -0.000003
13            -0.000086            0.000017
14             0.000170           -0.000040
15            -0.000058            0.000088
16             0.000061            0.000065
17            -0.000026           -0.000039
18             0.000113           -0.000018
19             0.000011           -0.000002

    p-(trifluoromethyl)benzaldehyde_1.txt  p-iodoanisole_3.txt  \
0                                0.000788            -0.000152
1                                0.000343             0.000600
2                               -0.000548            -0.000146
3                               -0.000148             0.000119
4                                0.000245            -0.000368
5                                0.000033             0.000014
6                               -0.000078            -0.000014
7                                0.000021             0.000050
8                               -0.000155            -0.000038
9                                0.000003             0.000065
10                               0.000151             0.000007
11                              -0.000148             0.000052
12                              -0.000075            -0.000006
13                              -0.000050            -0.000087
14                               0.000081             0.000166
15                               0.000104            -0.000057
16                              -0.000007             0.000060
17                               0.000065            -0.000025
18                               0.000061             0.000115
19                               0.000046             0.000011

    p-acetamidophenol_5.txt
0             -5.417324e-04
1              1.054908e-04
2              1.837241e-04
3              2.919290e-04
4              1.816122e-04
5              1.186128e-04
6             -2.246519e-04
7             -1.358130e-04
8             -1.297139e-04
9              1.967263e-04
10            -4.617411e-05
11             9.489480e-05
12            -1.148867e-04
13            -4.566016e-05
14            -6.474664e-05
15            -9.179449e-05
16             4.328906e-05
17             6.585322e-06
18             8.733136e-07
19            -3.648677e-05

[20 rows x 380 columns]

,o-salicylaldehyde,o-1-chloro-2-nitrobenzene,o-salicylic acid,o-guaiacol,o-aminobenzylalcohol,m-tolualdehyde,o-bromotoluene,m-toluoyl chloride,p-acetoxybenzoic,m-aminoacetophenone,...,p-(trifluoromethyl)benzaldehyde,p-aminophenol,p-hydroxybenzoic acid,p-tolualdehyde,p-iodoanisole,p-iodoanisole,p-iodophenol,p-(trifluoromethyl)benzaldehyde,p-iodoanisole,p-acetamidophenol
630.0,0.000186,0.000212,0.000170,0.000241,0.000148,0.000266,0.000294,0.000250,0.000233,0.000209,...,0.000293,0.000246,0.000222,0.000298,0.000236,0.000236,0.000153,0.000289,0.000235,0.000183
631.0,0.000184,0.000211,0.000166,0.000240,0.000147,0.000264,0.000291,0.000249,0.000230,0.000209,...,0.000294,0.000245,0.000222,0.000297,0.000235,0.000234,0.000162,0.000292,0.000236,0.000185
632.0,0.000178,0.000209,0.000168,0.000240,0.000147,0.000262,0.000291,0.000246,0.000228,0.000207,...,0.000295,0.000246,0.000221,0.000297,0.000236,0.000233,0.000164,0.000294,0.000236,0.000186
633.0,0.000173,0.000207,0.000164,0.000242,0.000147,0.000259,0.000291,0.000243,0.000225,0.000206,...,0.000296,0.000246,0.000219,0.000296,0.000236,0.000234,0.000145,0.000295,0.000235,0.000187
634.0,0.000171,0.000204,0.000162,0.000241,0.000146,0.000256,0.000291,0.000240,0.000226,0.000204,...,0.000295,0.000247,0.000216,0.000296,0.000235,0.000235,0.000143,0.000298,0.000234,0.000185

---

### Train/Test Splits

When testing the success of a machine learning algorithm, a dataset is typically divided into two, a training dataset and a test dataset.
<br>
<br>The training dataset is the information that is passed to the algorithm and what it bases its 'learning' on. While the test dataset is used as a benchmark to see how well the algorithm can predict the right result (correctly identify data subsets) after learning from the training set.
<br>
<br> When assigning train-test splits, i.e. dividing the data into the two subsets, it is important that datasets containing repeated measurements are treated so that all repeats are passed into the same one of the two sets. Consider a case in which four of five repeated measurements are passed to the training dataset and the remaining one is passed to the test dataset. Since the algorithm will have encountered four instances of the same data already within the training dataset, it is highly likely that it will succesfully assign the final repeat in the test dataset. As a result, the apparent success of the machine learning is overexaggerated and not a true representation of the success of the machine learning.
<br>
<br>Thus, while it is useful to save spectra with numbers indicating different repeats (computers do not like files with exactly the same name), it is now best to rename the data so that these repeat indicators are removed.

In [4]:
column_names = []
for i in os.scandir("/content/drive/MyDrive/Raw_IR_Spectra"):
  column_names.append(i.name)
print(column_names)

['o-salicylaldehyde_4.txt', 'o-1-chloro-2-nitrobenzene_3.txt', 'o-salicylic acid_4.txt', 'o-guaiacol_3.txt', 'o-aminobenzylalcohol_3.txt', 'm-tolualdehyde_3.txt', 'o-bromotoluene_3.txt', 'm-toluoyl chloride_3.txt', 'p-acetoxybenzoic_2.txt', 'm-aminoacetophenone_1.txt', 'o-anthranilicacid_4.txt', 'm-tolualdehyde_4.txt', 'o-aspirin_5.txt', 'o-dicyanobenzene_3.txt', 'o-ethoxyphenol_5.txt', 'p-allylphenoxide_2.txt', 'o-fluorobenzaldehyde_5.txt', 'o-chlorobenzaldehyde_3.txt', 'o-toluidine_1.txt', 'm-diethoxybenzene_5.txt', 'm-toluenesulfonyl chloride_4.txt', 'p-hydroxybenzamide_1.txt', 'm-methyl o-toluate_5.txt', 'p-bromotoluene_3.txt', 'o-aminobenzylamine_3.txt', 'm-acetoxybenzoic_4.txt', 'm-nitrotoluene_3.txt', 'm-aminoacetophenone_4.txt', 'o-hydroxybenzonitrile_3.txt', 'o-guaiacol_5.txt', 'p-allylphenoxide_1.txt', 'o-fluorobenzaldehyde_2.txt', 'o-toluidine_4.txt', 'o-methylacetophenone_2.txt', 'o-dicyanobenzene_5.txt', 'p-bromoacetophenone_4.txt', 'p-cyanobenzaldehyde_1.txt', 'm-methyl o-toluate_4.txt', 'o-1-chloro-2-nitrobenzene_1.txt', 'p-dimethoxybenzene_2.txt', 'm-tolualdehyde_2.txt', 'm-anisaldehyde_4.txt', 'p-bromotoluene_5.txt', 'm-diacetoxybenzene_4.txt', 'm-bromobenzaldehyde_2.txt', 'm-toluenesulfonyl chloride_2.txt', 'o-hydroxybenzonitrile_4.txt', 'o-chlorobenzaldehyde_1.txt', 'm-nitrophenol_3.txt', 'p-trans-anethole_2.txt', 'o-fluorophenol_5.txt', 'm-fluorophenol_2.txt', 'm-diacetoxybenzene_2.txt', 'm-hydroxybenzonitrile_4.txt', 'o-hydroxybenzonitrile_2.txt', 'm-methoxyphenol_4.txt', 'o-dichlorobenzene_4.txt', 'm-toluicacid_4.txt', 'm-methyl o-toluate_3.txt', 'p-hydroxybenzaldehyde_4.txt', 'o-salicylaldehyde_2.txt', 'o-anthranilicacid_3.txt', 'm-bromobenzaldehyde_4.txt', 'p-hydroxybenzaldehyde_1.txt', 'o-dichlorobenzene_3.txt', 'p-cyanobenzaldehyde_4.txt', 'm-nitrophenol_1.txt', 'p-chlorobenzaldehyde_2.txt', 'o-bromotoluene_4.txt', 'm-acetoxybenzoic_3.txt', 'p-bromobenzoic acid_4.txt', 'o-hydroxyacetophenone_3.txt', 'm-toluoyl chloride_2.txt', 'm-nitroacetophenone_5.txt', 'm-methoxyphenol_2.txt', 'o-1-chloro-2-nitrobenzene_2.txt', 'm-diacetoxybenzene_5.txt', 'o-chlorobenzaldehyde_4.txt', 'm-toluicacid_2.txt', 'm-diacetoxybenzene_1.txt', 'o-dicyanobenzene_2.txt', 'o-fluorophenol_1.txt', 'p-dimethoxybenzene_1.txt', 'p-hydroxybenzaldehyde_5.txt', 'p-bromobenzoic acid_1.txt', 'p-bromobenzaldehyde_4.txt', 'o-aspirin_1.txt', 'p-bromobenzaldehyde_5.txt', 'o-methylacetophenone_4.txt', 'm-acetoxybenzoic_1.txt', 'o-salicylaldehyde_1.txt', 'o-hydroxyacetophenone_5.txt', 'm-anisaldehyde_1.txt', 'o-tolualdehyde_2.txt', 'm-nitrotoluene_5.txt', 'p-acetaminophen_1.txt', 'm-dimethoxybenzene_5.txt', 'm-diacetylbenzene_3.txt', 'm-methoxyphenol_3.txt', 'o-tolualdehyde_5.txt', 'p-hydroxybenzamide_4.txt', 'm-bromobenzaldehyde_5.txt', 'm-aminoacetophenone_5.txt', 'o-ethoxyphenol_4.txt', 'm-methyl o-aminobenzoate_5.txt', 'm-aminoacetophenone_3.txt', 'm-diethoxybenzene_4.txt', 'm-methyl o-toluate_2.txt', 'o-dichlorobenzene_1.txt', 'p-acetaminophen_4.txt', 'p-chloroaniline_2.txt', 'o-anthranilicacid_2.txt', 'p-acetoxybenzoic_5.txt', 'o-dichlorobenzene_2.txt', 'o-toluidine_5.txt', 'o-bromotoluene_5.txt', 'm-hydroxybenzonitrile_5.txt', 'm-acetoxybenzoic_5.txt', 'o-chlorobenzaldehyde_2.txt', 'o-ethoxyphenol_3.txt', 'm-methoxybenzaldehyde_4.txt', 'm-diacetylbenzene_1.txt', 'o-aminobenzylamine_1.txt', 'm-dimethoxybenzene_2.txt', 'p-cyanobenzaldehyde_2.txt', 'm-toluicacid_3.txt', 'm-toluoyl chloride_1.txt', 'm-anisaldehyde_5.txt', 'm-nitrotoluene_4.txt', 'o-aminobenzylalcohol_2.txt', 'p-acetoxybenzoic_1.txt', 'p-hydroxybenzaldehyde_2.txt', 'm-chloroperbenzoicacid_3.txt', 'o-dihydroxybenzene_3.txt', 'o-aminobenzylamine_5.txt', 'o-tolualdehyde_1.txt', 'm-methoxybenzaldehyde_3.txt', 'm-methoxybenzaldehyde_2.txt', 'o-hydroxyacetophenone_2.txt', 'm-diacetylbenzene_2.txt', 'o-methylacetophenone_5.txt', 'p-acetoxybenzoic_4.txt', 'm-fluorophenol_3.txt', 'o-ethoxyphenol_2.txt', 'p-dimethoxybenzene_5.txt', 'p-cyanophenol_2.txt', 'p-xylylenediamine_1.txt', 'p-bromotoluene_1.txt', 'o-aminobenzylalcohol_1.txt', 'm-acetoxybenzoic_2.txt', 'o-1-chloro-2-nitrobenzene_5.txt', 'o-dicyanobenzene_4.txt', 'p-acetaminophen_3.txt', 'p-bromobenzoic acid_3.txt', 'm-toluoyl chloride_4.txt', 'm-toluoyl chloride_5.txt', 'p-chlorobenzaldehyde_4.txt', 'o-anthranilicacid_1.txt', 'o-fluorobenzaldehyde_4.txt', 'o-salicylic acid_1.txt', 'o-aspirin_3.txt', 'm-aminoacetophenone_2.txt', 'm-methoxybenzaldehyde_1.txt', 'm-bromobenzaldehyde_1.txt', 'm-toluicacid_1.txt', 'm-methyl o-aminobenzoate_3.txt', 'p-dimethoxybenzene_3.txt', 'o-hydroxyacetophenone_4.txt', 'p-trans-anethole_4.txt', 'o-guaiacol_4.txt', 'm-nitrophenol_2.txt', 'o-tolualdehyde_3.txt', 'p-acetaminophen_2.txt', 'p-bromobenzaldehyde_1.txt', 'm-methyl o-aminobenzoate_1.txt', 'm-toluenesulfonyl chloride_3.txt', 'o-salicylaldehyde_3.txt', 'm-diacetylbenzene_5.txt', 'p-cyanophenol_5.txt', 'm-hydroxybenzonitrile_3.txt', 'o-fluorobenzaldehyde_1.txt', 'p-allylphenoxide_5.txt', 'p-bromoacetophenone_3.txt', 'm-toluenesulfonyl chloride_1.txt', 'o-toluidine_3.txt', 'm-toluicacid_5.txt', 'o-fluorophenol_4.txt', 'o-aspirin_2.txt', 'm-fluorophenol_4.txt', 'm-methoxybenzaldehyde_5.txt', 'o-dihydroxybenzene_4.txt', 'o-anthranilicacid_5.txt', 'm-diethoxybenzene_3.txt', 'p-xylylenediamine_2.txt', 'o-aminobenzylamine_2.txt', 'p-bromobenzaldehyde_2.txt', 'm-chloroperbenzoicacid_1.txt', 'm-methoxyphenol_1.txt', 'o-1-chloro-2-nitrobenzene_4.txt', 'm-diacetoxybenzene_3.txt', 'm-dimethoxybenzene_3.txt', 'o-fluorobenzaldehyde_3.txt', 'm-nitroacetophenone_1.txt', 'o-guaiacol_1.txt', 'm-dimethoxybenzene_1.txt', 'p-chlorobenzaldehyde_3.txt', 'm-nitroacetophenone_2.txt', 'p-hydroxybenzaldehyde_3.txt', 'o-dihydroxybenzene_2.txt', 'o-guaiacol_2.txt', 'm-methyl o-aminobenzoate_2.txt', 'm-nitrophenol_4.txt', 'o-dicyanobenzene_1.txt', 'p-bromotoluene_4.txt', 'm-diethoxybenzene_1.txt', 'o-tolualdehyde_4.txt', 'p-bromobenzaldehyde_3.txt', 'p-hydroxybenzamide_2.txt', 'p-cyanophenol_1.txt', 'm-nitrotoluene_1.txt', 'm-fluorophenol_5.txt', 'm-chloroperbenzoicacid_5.txt', 'o-dichlorobenzene_5.txt', 'm-chloroperbenzoicacid_2.txt', 'm-methoxyphenol_5.txt', 'o-ethoxyphenol_1.txt', 'p-chlorobenzaldehyde_5.txt', 'p-cyanobenzaldehyde_3.txt', 'm-methyl o-toluate_1.txt', 'p-chloroaniline_4.txt', 'p-chloroaniline_3.txt', 'p-bromoacetophenone_2.txt', 'm-anisaldehyde_3.txt', 'o-hydroxybenzonitrile_5.txt', 'p-bromoacetophenone_5.txt', 'm-hydroxybenzonitrile_1.txt', 'm-methyl o-aminobenzoate_4.txt', 'm-hydroxybenzonitrile_2.txt', 'o-dihydroxybenzene_1.txt', 'o-salicylic acid_5.txt', 'p-hydroxybenzamide_5.txt', 'm-chloroperbenzoicacid_4.txt', 'm-diacetylbenzene_4.txt', 'o-bromotoluene_2.txt', 'o-salicylaldehyde_5.txt', 'o-fluorophenol_3.txt', 'o-aminobenzylamine_4.txt', 'o-aminobenzylalcohol_4.txt', 'o-hydroxyacetophenone_1.txt', 'p-trans-anethole_1.txt', 'm-tolualdehyde_1.txt', 'o-fluorophenol_2.txt', 'p-cyanophenol_3.txt', 'm-nitrophenol_5.txt', 'p-bromobenzoic acid_2.txt', 'p-bromoacetophenone_1.txt', 'o-hydroxybenzonitrile_1.txt', 'm-dimethoxybenzene_4.txt', 'm-anisaldehyde_2.txt', 'o-aspirin_4.txt', 'm-nitroacetophenone_4.txt', 'p-allylphenoxide_4.txt', 'm-toluenesulfonyl chloride_5.txt', 'm-nitrotoluene_2.txt', 'o-aminobenzylalcohol_5.txt', 'm-fluorophenol_1.txt', 'o-bromotoluene_1.txt', 'm-diethoxybenzene_2.txt', 'm-bromobenzaldehyde_3.txt', 'p-chloroaniline_5.txt', 'o-salicylic acid_2.txt', 'o-chlorobenzaldehyde_5.txt', 'p-bromotoluene_2.txt', 'p-dimethoxybenzene_4.txt', 'p-chloroaniline_1.txt', 'o-salicylic acid_3.txt', 'm-tolualdehyde_5.txt', 'o-dihydroxybenzene_5.txt', 'p-hydroxybenzamide_3.txt', 'p-allylphenoxide_3.txt', 'p-bromobenzoic acid_5.txt', 'm-nitroacetophenone_3.txt', 'p-acetaminophen_5.txt', 'p-trans-anethole_5.txt', 'o-methylacetophenone_3.txt', 'p-trans-anethole_3.txt', 'p-cyanobenzaldehyde_5.txt', 'o-methylacetophenone_1.txt', 'p-chlorobenzaldehyde_1.txt', 'p-acetoxybenzoic_3.txt', 'o-toluidine_2.txt', 'p-cyanophenol_4.txt', 'p-fluoroacetophenone_2.txt', 'p-fluoroaniline_4.txt', 'p-xylene_2.txt', 'p-(trifluoromethyl)acetophenone_5.txt', 'p-nitroacetophenone_2.txt', 'p-xylene_4.txt', 'p-toluenesulfonamide_2.txt', 'p-acetamidophenol_1.txt', 'p-iodophenol_5.txt', 'p-toluidine_2.txt', 'p-hydroxybenzoic acid_3.txt', 'p-aminobenzoic_1.txt', 'p-toluidine_3.txt', 'p-xylylenediamine_3.txt', 'p-acetamidophenol_4.txt', 'p-toluidine_1.txt', 'p-nitrotoluene_3.txt', 'p-tolualdehyde_5.txt', 'p-nitrotoluene_2.txt', 'p-aminophenol_2.txt', 'p-iodophenol_2.txt', 'p-toluenesulfonamide_1.txt', 'p-toluidine_5.txt', 'p-toluenesulfonamide_3.txt', 'p-aminophenol_3.txt', 'p-aminobenzoic_5.txt', 'p-(trifluoromethyl)benzaldehyde_3.txt', 'p-fluoroaniline_3.txt', 'p-nitroacetophenone_5.txt', 'p-fluoroaniline_5.txt', 'p-(trifluoromethyl)acetophenone_2.txt', 'p-fluoroacetophenone_4.txt', 'p-toluenesulfonyl chloride_4.txt', 'p-hydroxybenzoic acid_5.txt', 'p-iodophenol_1.txt', 'p-nitrotoluene_1.txt', 'p-nitroacetophenone_3.txt', 'p-(trifluoromethyl)acetophenone_1.txt', 'p-toluenesulfonyl chloride_3.txt', 'p-fluoroacetophenone_3.txt', 'p-xylene_5.txt', 'p-iodoanisole_1.txt', 'p-aminobenzoic_3.txt', 'p-tolualdehyde_3.txt', 'p-toluenesulfonyl chloride_1.txt', 'p-acetamidophenol_3.txt', 'p-toluenesulfonyl chloride_2.txt', 'p-toluenesulfonyl chloride_5.txt', 'p-toluenesulfonamide_5.txt', 'p-aminophenol_5.txt', 'p-xylene_1.txt', 'p-nitroacetophenone_4.txt', 'p-hydroxybenzoic acid_2.txt', 'p-toluenesulfonamide_4.txt', 'p-nitroacetophenone_1.txt', 'p-iodophenol_3.txt', 'p-(trifluoromethyl)acetophenone_3.txt', 'p-nitrotoluene_5.txt', 'p-aminobenzoic_2.txt', 'p-xylylenediamine_4.txt', 'p-hydroxybenzoic acid_4.txt', 'p-tolualdehyde_2.txt', 'p-fluoroacetophenone_1.txt', 'p-xylylenediamine_5.txt', 'p-aminobenzoic_4.txt', 'p-(trifluoromethyl)benzaldehyde_5.txt', 'p-fluoroaniline_1.txt', 'p-iodoanisole_5.txt', 'p-fluoroacetophenone_5.txt', 'p-aminophenol_1.txt', 'p-toluidine_4.txt', 'p-xylene_3.txt', 'p-tolualdehyde_1.txt', 'p-(trifluoromethyl)benzaldehyde_4.txt', 'p-fluoroaniline_2.txt', 'p-acetamidophenol_2.txt', 'p-nitrotoluene_4.txt', 'p-(trifluoromethyl)acetophenone_4.txt', 'p-(trifluoromethyl)benzaldehyde_2.txt', 'p-aminophenol_4.txt', 'p-hydroxybenzoic acid_1.txt', 'p-tolualdehyde_4.txt', 'p-iodoanisole_2.txt', 'p-iodoanisole_4.txt', 'p-iodophenol_4.txt', 'p-(trifluoromethyl)benzaldehyde_1.txt', 'p-iodoanisole_3.txt', 'p-acetamidophenol_5.txt']

In [5]:
# re.split(pattern, string, maxsplit=0, flags=0)
# re.split(r'\W+', 'Words, words, words.')
import re
columns_identical = []
for i in column_names:
  columns_identical.append(re.split(r'\_+', i)[0])

print(columns_identical)

['o-salicylaldehyde', 'o-1-chloro-2-nitrobenzene', 'o-salicylic acid', 'o-guaiacol', 'o-aminobenzylalcohol', 'm-tolualdehyde', 'o-bromotoluene', 'm-toluoyl chloride', 'p-acetoxybenzoic', 'm-aminoacetophenone', 'o-anthranilicacid', 'm-tolualdehyde', 'o-aspirin', 'o-dicyanobenzene', 'o-ethoxyphenol', 'p-allylphenoxide', 'o-fluorobenzaldehyde', 'o-chlorobenzaldehyde', 'o-toluidine', 'm-diethoxybenzene', 'm-toluenesulfonyl chloride', 'p-hydroxybenzamide', 'm-methyl o-toluate', 'p-bromotoluene', 'o-aminobenzylamine', 'm-acetoxybenzoic', 'm-nitrotoluene', 'm-aminoacetophenone', 'o-hydroxybenzonitrile', 'o-guaiacol', 'p-allylphenoxide', 'o-fluorobenzaldehyde', 'o-toluidine', 'o-methylacetophenone', 'o-dicyanobenzene', 'p-bromoacetophenone', 'p-cyanobenzaldehyde', 'm-methyl o-toluate', 'o-1-chloro-2-nitrobenzene', 'p-dimethoxybenzene', 'm-tolualdehyde', 'm-anisaldehyde', 'p-bromotoluene', 'm-diacetoxybenzene', 'm-bromobenzaldehyde', 'm-toluenesulfonyl chloride', 'o-hydroxybenzonitrile', 'o-chlorobenzaldehyde', 'm-nitrophenol', 'p-trans-anethole', 'o-fluorophenol', 'm-fluorophenol', 'm-diacetoxybenzene', 'm-hydroxybenzonitrile', 'o-hydroxybenzonitrile', 'm-methoxyphenol', 'o-dichlorobenzene', 'm-toluicacid', 'm-methyl o-toluate', 'p-hydroxybenzaldehyde', 'o-salicylaldehyde', 'o-anthranilicacid', 'm-bromobenzaldehyde', 'p-hydroxybenzaldehyde', 'o-dichlorobenzene', 'p-cyanobenzaldehyde', 'm-nitrophenol', 'p-chlorobenzaldehyde', 'o-bromotoluene', 'm-acetoxybenzoic', 'p-bromobenzoic acid', 'o-hydroxyacetophenone', 'm-toluoyl chloride', 'm-nitroacetophenone', 'm-methoxyphenol', 'o-1-chloro-2-nitrobenzene', 'm-diacetoxybenzene', 'o-chlorobenzaldehyde', 'm-toluicacid', 'm-diacetoxybenzene', 'o-dicyanobenzene', 'o-fluorophenol', 'p-dimethoxybenzene', 'p-hydroxybenzaldehyde', 'p-bromobenzoic acid', 'p-bromobenzaldehyde', 'o-aspirin', 'p-bromobenzaldehyde', 'o-methylacetophenone', 'm-acetoxybenzoic', 'o-salicylaldehyde', 'o-hydroxyacetophenone', 'm-anisaldehyde', 'o-tolualdehyde', 'm-nitrotoluene', 'p-acetaminophen', 'm-dimethoxybenzene', 'm-diacetylbenzene', 'm-methoxyphenol', 'o-tolualdehyde', 'p-hydroxybenzamide', 'm-bromobenzaldehyde', 'm-aminoacetophenone', 'o-ethoxyphenol', 'm-methyl o-aminobenzoate', 'm-aminoacetophenone', 'm-diethoxybenzene', 'm-methyl o-toluate', 'o-dichlorobenzene', 'p-acetaminophen', 'p-chloroaniline', 'o-anthranilicacid', 'p-acetoxybenzoic', 'o-dichlorobenzene', 'o-toluidine', 'o-bromotoluene', 'm-hydroxybenzonitrile', 'm-acetoxybenzoic', 'o-chlorobenzaldehyde', 'o-ethoxyphenol', 'm-methoxybenzaldehyde', 'm-diacetylbenzene', 'o-aminobenzylamine', 'm-dimethoxybenzene', 'p-cyanobenzaldehyde', 'm-toluicacid', 'm-toluoyl chloride', 'm-anisaldehyde', 'm-nitrotoluene', 'o-aminobenzylalcohol', 'p-acetoxybenzoic', 'p-hydroxybenzaldehyde', 'm-chloroperbenzoicacid', 'o-dihydroxybenzene', 'o-aminobenzylamine', 'o-tolualdehyde', 'm-methoxybenzaldehyde', 'm-methoxybenzaldehyde', 'o-hydroxyacetophenone', 'm-diacetylbenzene', 'o-methylacetophenone', 'p-acetoxybenzoic', 'm-fluorophenol', 'o-ethoxyphenol', 'p-dimethoxybenzene', 'p-cyanophenol', 'p-xylylenediamine', 'p-bromotoluene', 'o-aminobenzylalcohol', 'm-acetoxybenzoic', 'o-1-chloro-2-nitrobenzene', 'o-dicyanobenzene', 'p-acetaminophen', 'p-bromobenzoic acid', 'm-toluoyl chloride', 'm-toluoyl chloride', 'p-chlorobenzaldehyde', 'o-anthranilicacid', 'o-fluorobenzaldehyde', 'o-salicylic acid', 'o-aspirin', 'm-aminoacetophenone', 'm-methoxybenzaldehyde', 'm-bromobenzaldehyde', 'm-toluicacid', 'm-methyl o-aminobenzoate', 'p-dimethoxybenzene', 'o-hydroxyacetophenone', 'p-trans-anethole', 'o-guaiacol', 'm-nitrophenol', 'o-tolualdehyde', 'p-acetaminophen', 'p-bromobenzaldehyde', 'm-methyl o-aminobenzoate', 'm-toluenesulfonyl chloride', 'o-salicylaldehyde', 'm-diacetylbenzene', 'p-cyanophenol', 'm-hydroxybenzonitrile', 'o-fluorobenzaldehyde', 'p-allylphenoxide', 'p-bromoacetophenone', 'm-toluenesulfonyl chloride', 'o-toluidine', 'm-toluicacid', 'o-fluorophenol', 'o-aspirin', 'm-fluorophenol', 'm-methoxybenzaldehyde', 'o-dihydroxybenzene', 'o-anthranilicacid', 'm-diethoxybenzene', 'p-xylylenediamine', 'o-aminobenzylamine', 'p-bromobenzaldehyde', 'm-chloroperbenzoicacid', 'm-methoxyphenol', 'o-1-chloro-2-nitrobenzene', 'm-diacetoxybenzene', 'm-dimethoxybenzene', 'o-fluorobenzaldehyde', 'm-nitroacetophenone', 'o-guaiacol', 'm-dimethoxybenzene', 'p-chlorobenzaldehyde', 'm-nitroacetophenone', 'p-hydroxybenzaldehyde', 'o-dihydroxybenzene', 'o-guaiacol', 'm-methyl o-aminobenzoate', 'm-nitrophenol', 'o-dicyanobenzene', 'p-bromotoluene', 'm-diethoxybenzene', 'o-tolualdehyde', 'p-bromobenzaldehyde', 'p-hydroxybenzamide', 'p-cyanophenol', 'm-nitrotoluene', 'm-fluorophenol', 'm-chloroperbenzoicacid', 'o-dichlorobenzene', 'm-chloroperbenzoicacid', 'm-methoxyphenol', 'o-ethoxyphenol', 'p-chlorobenzaldehyde', 'p-cyanobenzaldehyde', 'm-methyl o-toluate', 'p-chloroaniline', 'p-chloroaniline', 'p-bromoacetophenone', 'm-anisaldehyde', 'o-hydroxybenzonitrile', 'p-bromoacetophenone', 'm-hydroxybenzonitrile', 'm-methyl o-aminobenzoate', 'm-hydroxybenzonitrile', 'o-dihydroxybenzene', 'o-salicylic acid', 'p-hydroxybenzamide', 'm-chloroperbenzoicacid', 'm-diacetylbenzene', 'o-bromotoluene', 'o-salicylaldehyde', 'o-fluorophenol', 'o-aminobenzylamine', 'o-aminobenzylalcohol', 'o-hydroxyacetophenone', 'p-trans-anethole', 'm-tolualdehyde', 'o-fluorophenol', 'p-cyanophenol', 'm-nitrophenol', 'p-bromobenzoic acid', 'p-bromoacetophenone', 'o-hydroxybenzonitrile', 'm-dimethoxybenzene', 'm-anisaldehyde', 'o-aspirin', 'm-nitroacetophenone', 'p-allylphenoxide', 'm-toluenesulfonyl chloride', 'm-nitrotoluene', 'o-aminobenzylalcohol', 'm-fluorophenol', 'o-bromotoluene', 'm-diethoxybenzene', 'm-bromobenzaldehyde', 'p-chloroaniline', 'o-salicylic acid', 'o-chlorobenzaldehyde', 'p-bromotoluene', 'p-dimethoxybenzene', 'p-chloroaniline', 'o-salicylic acid', 'm-tolualdehyde', 'o-dihydroxybenzene', 'p-hydroxybenzamide', 'p-allylphenoxide', 'p-bromobenzoic acid', 'm-nitroacetophenone', 'p-acetaminophen', 'p-trans-anethole', 'o-methylacetophenone', 'p-trans-anethole', 'p-cyanobenzaldehyde', 'o-methylacetophenone', 'p-chlorobenzaldehyde', 'p-acetoxybenzoic', 'o-toluidine', 'p-cyanophenol', 'p-fluoroacetophenone', 'p-fluoroaniline', 'p-xylene', 'p-(trifluoromethyl)acetophenone', 'p-nitroacetophenone', 'p-xylene', 'p-toluenesulfonamide', 'p-acetamidophenol', 'p-iodophenol', 'p-toluidine', 'p-hydroxybenzoic acid', 'p-aminobenzoic', 'p-toluidine', 'p-xylylenediamine', 'p-acetamidophenol', 'p-toluidine', 'p-nitrotoluene', 'p-tolualdehyde', 'p-nitrotoluene', 'p-aminophenol', 'p-iodophenol', 'p-toluenesulfonamide', 'p-toluidine', 'p-toluenesulfonamide', 'p-aminophenol', 'p-aminobenzoic', 'p-(trifluoromethyl)benzaldehyde', 'p-fluoroaniline', 'p-nitroacetophenone', 'p-fluoroaniline', 'p-(trifluoromethyl)acetophenone', 'p-fluoroacetophenone', 'p-toluenesulfonyl chloride', 'p-hydroxybenzoic acid', 'p-iodophenol', 'p-nitrotoluene', 'p-nitroacetophenone', 'p-(trifluoromethyl)acetophenone', 'p-toluenesulfonyl chloride', 'p-fluoroacetophenone', 'p-xylene', 'p-iodoanisole', 'p-aminobenzoic', 'p-tolualdehyde', 'p-toluenesulfonyl chloride', 'p-acetamidophenol', 'p-toluenesulfonyl chloride', 'p-toluenesulfonyl chloride', 'p-toluenesulfonamide', 'p-aminophenol', 'p-xylene', 'p-nitroacetophenone', 'p-hydroxybenzoic acid', 'p-toluenesulfonamide', 'p-nitroacetophenone', 'p-iodophenol', 'p-(trifluoromethyl)acetophenone', 'p-nitrotoluene', 'p-aminobenzoic', 'p-xylylenediamine', 'p-hydroxybenzoic acid', 'p-tolualdehyde', 'p-fluoroacetophenone', 'p-xylylenediamine', 'p-aminobenzoic', 'p-(trifluoromethyl)benzaldehyde', 'p-fluoroaniline', 'p-iodoanisole', 'p-fluoroacetophenone', 'p-aminophenol', 'p-toluidine', 'p-xylene', 'p-tolualdehyde', 'p-(trifluoromethyl)benzaldehyde', 'p-fluoroaniline', 'p-acetamidophenol', 'p-nitrotoluene', 'p-(trifluoromethyl)acetophenone', 'p-(trifluoromethyl)benzaldehyde', 'p-aminophenol', 'p-hydroxybenzoic acid', 'p-tolualdehyde', 'p-iodoanisole', 'p-iodoanisole', 'p-iodophenol', 'p-(trifluoromethyl)benzaldehyde', 'p-iodoanisole', 'p-acetamidophenol']

Recall that the column titles of a DataFrame can be overwritten by just setting the `.columns` attribute of the DataFrame to the new list of column titles.

In [6]:
import importlib
importlib.reload(C317)

a = C317.load_spectra(20)
a.columns = columns_identical # I didn't know this way of using .columns attribute
a.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
    o-salicylaldehyde_4.txt  o-1-chloro-2-nitrobenzene_3.txt  \
0                 -0.000849                        -0.000447
1                 -0.000827                        -0.000170
2                  0.000180                        -0.000037
3                 -0.000098                         0.000216
4                  0.000221                         0.000097
5                  0.000331                        -0.000463
6                 -0.000040                        -0.000401
7                 -0.000173                        -0.000320
8                  0.000206                         0.000248
9                  0.000183                        -0.000332
10                 0.000043                        -0.000127
11                -0.000053                         0.000103
12                 0.000097                         0.000150
13                -0.000143                         0.000010
14                -0.000007                         0.000118
15                -0.000079                         0.000116
16                -0.000077                         0.000003
17                -0.000089                         0.000032
18                 0.000014                        -0.000042
19                 0.000065                         0.000115

    o-salicylic acid_4.txt  o-guaiacol_3.txt  o-aminobenzylalcohol_3.txt  \
0                -0.000650          0.000264                   -0.001211
1                -0.000150         -0.000794                   -0.000081
2                 0.000207         -0.000320                   -0.000219
3                -0.000342          0.000238                    0.000103
4                 0.000236         -0.000048                   -0.000125
5                 0.000031         -0.000004                   -0.000163
6                 0.000258         -0.000064                    0.000030
7                 0.000061          0.000008                    0.000035
8                -0.000035         -0.000012                   -0.000038
9                -0.000028          0.000105                    0.000088
10               -0.000068          0.000033                   -0.000050
11                0.000092          0.000008                    0.000001
12               -0.000135         -0.000066                    0.000035
13               -0.000145          0.000010                    0.000004
14                0.000064          0.000033                   -0.000019
15                0.000163          0.000038                   -0.000033
16               -0.000006         -0.000026                    0.000013
17               -0.000018         -0.000034                    0.000021
18                0.000005         -0.000014                   -0.000023
19                0.000082         -0.000016                   -0.000059

    m-tolualdehyde_3.txt  o-bromotoluene_3.txt  m-toluoyl chloride_3.txt  \
0               0.000308              0.000714                 -0.000275
1              -0.000210             -0.000715                  0.000114
2               0.000486             -0.000010                  0.000717
3              -0.000157              0.000337                 -0.000320
4              -0.000137              0.000018                 -0.000256
5              -0.000133              0.000021                  0.000533
6              -0.000230              0.000148                 -0.000209
7               0.000349              0.000218                  0.000003
8               0.000094             -0.000104                 -0.000289
9               0.000014              0.000016                  0.000123
10              0.000044             -0.000003                 -0.000088
11              0.000201              0.000129                 -0.000173
12              0.000008              0.000149                  0.000393
13             -0.000074             -0.000081                 -0.000052
14              0.000052             -0.000002                  0.000002
15              0.000019             -0.000055                  0.000106
16             -0.000020              0.000036                  0.000171
17              0.000106              0.000064                 -0.000027
18             -0.000073             -0.000062                  0.000016
19              0.000115              0.000014                  0.000068

    p-acetoxybenzoic_2.txt  m-aminoacetophenone_1.txt  ...  \
0                -0.000250              -3.125144e-04  ...
1                 0.000321               1.389693e-04  ...
2                -0.000047               2.490830e-04  ...
3                -0.000260              -2.591943e-04  ...
4                 0.000085              -7.754741e-06  ...
5                -0.000101              -2.700181e-04  ...
6                 0.000445               2.456666e-05  ...
7                -0.000071               8.115776e-05  ...
8                -0.000127               1.512035e-04  ...
9                 0.000064              -5.290091e-05  ...
10               -0.000060               1.467278e-06  ...
11               -0.000117              -6.624794e-05  ...
12                0.000020              -4.823474e-05  ...
13               -0.000023              -1.288377e-04  ...
14                0.000090               7.450132e-05  ...
15                0.000197              -8.007511e-05  ...
16               -0.000018              -8.735301e-05  ...
17               -0.000089               8.429005e-05  ...
18                0.000034               9.126164e-07  ...
19               -0.000048              -1.133323e-04  ...

    p-(trifluoromethyl)benzaldehyde_2.txt  p-aminophenol_4.txt  \
0                                0.000787         3.421660e-04
1                                0.000344         1.174880e-04
2                               -0.000547        -5.866038e-05
3                               -0.000152         1.351596e-04
4                                0.000245        -3.358443e-06
5                                0.000033         3.224318e-06
6                               -0.000080         1.999217e-04
7                                0.000022         4.054251e-05
8                               -0.000153         1.197266e-04
9                                0.000004        -6.930083e-05
10                               0.000148        -5.373276e-05
11                              -0.000148         1.139648e-05
12                              -0.000075        -5.038029e-08
13                              -0.000051        -7.700107e-06
14                               0.000083        -6.085557e-06
15                               0.000104         3.166323e-06
16                              -0.000008        -3.611261e-05
17                               0.000065         3.420785e-05
18                               0.000062        -2.253766e-05
19                               0.000046        -4.515064e-05

    p-hydroxybenzoic acid_1.txt  p-tolualdehyde_4.txt  p-iodoanisole_2.txt  \
0                 -3.732225e-04              0.000777            -0.000086
1                  3.847578e-04              0.000289             0.000529
2                 -3.141540e-04             -0.000142            -0.000110
3                 -3.456790e-04             -0.000127             0.000107
4                  8.552972e-07             -0.000354            -0.000310
5                 -1.375584e-04              0.000327             0.000004
6                 -9.350100e-05              0.000105             0.000005
7                 -4.129683e-06             -0.000166             0.000034
8                 -1.303063e-04             -0.000158            -0.000020
9                 -2.507342e-04             -0.000216             0.000044
10                -1.408311e-04             -0.000200             0.000009
11                 1.257542e-05              0.000138             0.000047
12                 2.532603e-04             -0.000152            -0.000002
13                 8.435605e-05              0.000030            -0.000082
14                -9.274859e-05              0.000083             0.000142
15                 1.008913e-05             -0.000101            -0.000049
16                 8.983981e-05             -0.000092             0.000051
17                -3.267305e-05             -0.000077            -0.000022
18                 1.071078e-04              0.000055             0.000101
19                 3.097808e-05              0.000071             0.000006

    p-iodoanisole_4.txt  p-iodophenol_4.txt  \
0             -0.000152           -0.000282
1              0.000595            0.000385
2             -0.000137            0.000124
3              0.000123            0.000229
4             -0.000374           -0.000143
5              0.000018            0.000304
6             -0.000017            0.000015
7              0.000047            0.000181
8             -0.000039            0.000181
9              0.000068           -0.000174
10             0.000012           -0.000071
11             0.000057            0.000021
12            -0.000009           -0.000003
13            -0.000086            0.000017
14             0.000170           -0.000040
15            -0.000058            0.000088
16             0.000061            0.000065
17            -0.000026           -0.000039
18             0.000113           -0.000018
19             0.000011           -0.000002

    p-(trifluoromethyl)benzaldehyde_1.txt  p-iodoanisole_3.txt  \
0                                0.000788            -0.000152
1                                0.000343             0.000600
2                               -0.000548            -0.000146
3                               -0.000148             0.000119
4                                0.000245            -0.000368
5                                0.000033             0.000014
6                               -0.000078            -0.000014
7                                0.000021             0.000050
8                               -0.000155            -0.000038
9                                0.000003             0.000065
10                               0.000151             0.000007
11                              -0.000148             0.000052
12                              -0.000075            -0.000006
13                              -0.000050            -0.000087
14                               0.000081             0.000166
15                               0.000104            -0.000057
16                              -0.000007             0.000060
17                               0.000065            -0.000025
18                               0.000061             0.000115
19                               0.000046             0.000011

    p-acetamidophenol_5.txt
0             -5.417324e-04
1              1.054908e-04
2              1.837241e-04
3              2.919290e-04
4              1.816122e-04
5              1.186128e-04
6             -2.246519e-04
7             -1.358130e-04
8             -1.297139e-04
9              1.967263e-04
10            -4.617411e-05
11             9.489480e-05
12            -1.148867e-04
13            -4.566016e-05
14            -6.474664e-05
15            -9.179449e-05
16             4.328906e-05
17             6.585322e-06
18             8.733136e-07
19            -3.648677e-05

[20 rows x 380 columns]

,o-salicylaldehyde,o-1-chloro-2-nitrobenzene,o-salicylic acid,o-guaiacol,o-aminobenzylalcohol,m-tolualdehyde,o-bromotoluene,m-toluoyl chloride,p-acetoxybenzoic,m-aminoacetophenone,...,p-(trifluoromethyl)benzaldehyde,p-aminophenol,p-hydroxybenzoic acid,p-tolualdehyde,p-iodoanisole,p-iodoanisole,p-iodophenol,p-(trifluoromethyl)benzaldehyde,p-iodoanisole,p-acetamidophenol
630.0,0.000186,0.000212,0.000170,0.000241,0.000148,0.000266,0.000294,0.000250,0.000233,0.000209,...,0.000293,0.000246,0.000222,0.000298,0.000236,0.000236,0.000153,0.000289,0.000235,0.000183
631.0,0.000184,0.000211,0.000166,0.000240,0.000147,0.000264,0.000291,0.000249,0.000230,0.000209,...,0.000294,0.000245,0.000222,0.000297,0.000235,0.000234,0.000162,0.000292,0.000236,0.000185
632.0,0.000178,0.000209,0.000168,0.000240,0.000147,0.000262,0.000291,0.000246,0.000228,0.000207,...,0.000295,0.000246,0.000221,0.000297,0.000236,0.000233,0.000164,0.000294,0.000236,0.000186
633.0,0.000173,0.000207,0.000164,0.000242,0.000147,0.000259,0.000291,0.000243,0.000225,0.000206,...,0.000296,0.000246,0.000219,0.000296,0.000236,0.000234,0.000145,0.000295,0.000235,0.000187
634.0,0.000171,0.000204,0.000162,0.000241,0.000146,0.000256,0.000291,0.000240,0.000226,0.000204,...,0.000295,0.000247,0.000216,0.000296,0.000235,0.000235,0.000143,0.000298,0.000234,0.000185

In [7]:
# df[df.columns[0]]
# a[a.columns[1]]
# a.columns[1]

# df.loc["Melting point"]

a2 = a[["m-toluicacid"]].copy()
print(a2)

       m-toluicacid  m-toluicacid  m-toluicacid  m-toluicacid  m-toluicacid
630.0      0.000258      0.000254      0.000260      0.000250      0.000248
631.0      0.000258      0.000254      0.000261      0.000251      0.000250
632.0      0.000258      0.000255      0.000262      0.000249      0.000247
633.0      0.000256      0.000253      0.000261      0.000249      0.000252
634.0      0.000257      0.000254      0.000261      0.000249      0.000249
...             ...           ...           ...           ...           ...
876.0      0.000209      0.000205      0.000223      0.000201      0.000198
877.0      0.000206      0.000203      0.000222      0.000199      0.000195
878.0      0.000205      0.000199      0.000218      0.000197      0.000193
879.0      0.000203      0.000199      0.000217      0.000194      0.000190
880.0      0.000199      0.000197      0.000217      0.000192      0.000188

[251 rows x 5 columns]

Notice that now all five repeats stay together, which is what we wanted.

In [3]:
import importlib
import C317
importlib.reload(C317)

a = C317.load_spectra(20)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
    o-salicylaldehyde  o-1-chloro-2-nitrobenzene  o-salicylic acid  \
0           -0.000849                  -0.000447         -0.000650
1           -0.000827                  -0.000170         -0.000150
2            0.000180                  -0.000037          0.000207
3           -0.000098                   0.000216         -0.000342
4            0.000221                   0.000097          0.000236
5            0.000331                  -0.000463          0.000031
6           -0.000040                  -0.000401          0.000258
7           -0.000173                  -0.000320          0.000061
8            0.000206                   0.000248         -0.000035
9            0.000183                  -0.000332         -0.000028
10           0.000043                  -0.000127         -0.000068
11          -0.000053                   0.000103          0.000092
12           0.000097                   0.000150         -0.000135
13          -0.000143                   0.000010         -0.000145
14          -0.000007                   0.000118          0.000064
15          -0.000079                   0.000116          0.000163
16          -0.000077                   0.000003         -0.000006
17          -0.000089                   0.000032         -0.000018
18           0.000014                  -0.000042          0.000005
19           0.000065                   0.000115          0.000082

    o-guaiacol  o-aminobenzylalcohol  m-tolualdehyde  o-bromotoluene  \
0     0.000264             -0.001211        0.000308        0.000714
1    -0.000794             -0.000081       -0.000210       -0.000715
2    -0.000320             -0.000219        0.000486       -0.000010
3     0.000238              0.000103       -0.000157        0.000337
4    -0.000048             -0.000125       -0.000137        0.000018
5    -0.000004             -0.000163       -0.000133        0.000021
6    -0.000064              0.000030       -0.000230        0.000148
7     0.000008              0.000035        0.000349        0.000218
8    -0.000012             -0.000038        0.000094       -0.000104
9     0.000105              0.000088        0.000014        0.000016
10    0.000033             -0.000050        0.000044       -0.000003
11    0.000008              0.000001        0.000201        0.000129
12   -0.000066              0.000035        0.000008        0.000149
13    0.000010              0.000004       -0.000074       -0.000081
14    0.000033             -0.000019        0.000052       -0.000002
15    0.000038             -0.000033        0.000019       -0.000055
16   -0.000026              0.000013       -0.000020        0.000036
17   -0.000034              0.000021        0.000106        0.000064
18   -0.000014             -0.000023       -0.000073       -0.000062
19   -0.000016             -0.000059        0.000115        0.000014

    m-toluoyl chloride  p-acetoxybenzoic  m-aminoacetophenone  ...  \
0            -0.000275         -0.000250        -3.125144e-04  ...
1             0.000114          0.000321         1.389693e-04  ...
2             0.000717         -0.000047         2.490830e-04  ...
3            -0.000320         -0.000260        -2.591943e-04  ...
4            -0.000256          0.000085        -7.754741e-06  ...
5             0.000533         -0.000101        -2.700181e-04  ...
6            -0.000209          0.000445         2.456666e-05  ...
7             0.000003         -0.000071         8.115776e-05  ...
8            -0.000289         -0.000127         1.512035e-04  ...
9             0.000123          0.000064        -5.290091e-05  ...
10           -0.000088         -0.000060         1.467278e-06  ...
11           -0.000173         -0.000117        -6.624794e-05  ...
12            0.000393          0.000020        -4.823474e-05  ...
13           -0.000052         -0.000023        -1.288377e-04  ...
14            0.000002          0.000090         7.450132e-05  ...
15            0.000106          0.000197        -8.007511e-05  ...
16            0.000171         -0.000018        -8.735301e-05  ...
17           -0.000027         -0.000089         8.429005e-05  ...
18            0.000016          0.000034         9.126164e-07  ...
19            0.000068         -0.000048        -1.133323e-04  ...

    p-(trifluoromethyl)benzaldehyde  p-aminophenol  p-hydroxybenzoic acid  \
0                          0.000787   3.421660e-04          -3.732225e-04
1                          0.000344   1.174880e-04           3.847578e-04
2                         -0.000547  -5.866038e-05          -3.141540e-04
3                         -0.000152   1.351596e-04          -3.456790e-04
4                          0.000245  -3.358443e-06           8.552972e-07
5                          0.000033   3.224318e-06          -1.375584e-04
6                         -0.000080   1.999217e-04          -9.350100e-05
7                          0.000022   4.054251e-05          -4.129683e-06
8                         -0.000153   1.197266e-04          -1.303063e-04
9                          0.000004  -6.930083e-05          -2.507342e-04
10                         0.000148  -5.373276e-05          -1.408311e-04
11                        -0.000148   1.139648e-05           1.257542e-05
12                        -0.000075  -5.038029e-08           2.532603e-04
13                        -0.000051  -7.700107e-06           8.435605e-05
14                         0.000083  -6.085557e-06          -9.274859e-05
15                         0.000104   3.166323e-06           1.008913e-05
16                        -0.000008  -3.611261e-05           8.983981e-05
17                         0.000065   3.420785e-05          -3.267305e-05
18                         0.000062  -2.253766e-05           1.071078e-04
19                         0.000046  -4.515064e-05           3.097808e-05

    p-tolualdehyde  p-iodoanisole  p-iodoanisole  p-iodophenol  \
0         0.000777      -0.000086      -0.000152     -0.000282
1         0.000289       0.000529       0.000595      0.000385
2        -0.000142      -0.000110      -0.000137      0.000124
3        -0.000127       0.000107       0.000123      0.000229
4        -0.000354      -0.000310      -0.000374     -0.000143
5         0.000327       0.000004       0.000018      0.000304
6         0.000105       0.000005      -0.000017      0.000015
7        -0.000166       0.000034       0.000047      0.000181
8        -0.000158      -0.000020      -0.000039      0.000181
9        -0.000216       0.000044       0.000068     -0.000174
10       -0.000200       0.000009       0.000012     -0.000071
11        0.000138       0.000047       0.000057      0.000021
12       -0.000152      -0.000002      -0.000009     -0.000003
13        0.000030      -0.000082      -0.000086      0.000017
14        0.000083       0.000142       0.000170     -0.000040
15       -0.000101      -0.000049      -0.000058      0.000088
16       -0.000092       0.000051       0.000061      0.000065
17       -0.000077      -0.000022      -0.000026     -0.000039
18        0.000055       0.000101       0.000113     -0.000018
19        0.000071       0.000006       0.000011     -0.000002

    p-(trifluoromethyl)benzaldehyde  p-iodoanisole  p-acetamidophenol
0                          0.000788      -0.000152      -5.417324e-04
1                          0.000343       0.000600       1.054908e-04
2                         -0.000548      -0.000146       1.837241e-04
3                         -0.000148       0.000119       2.919290e-04
4                          0.000245      -0.000368       1.816122e-04
5                          0.000033       0.000014       1.186128e-04
6                         -0.000078      -0.000014      -2.246519e-04
7                          0.000021       0.000050      -1.358130e-04
8                         -0.000155      -0.000038      -1.297139e-04
9                          0.000003       0.000065       1.967263e-04
10                         0.000151       0.000007      -4.617411e-05
11                        -0.000148       0.000052       9.489480e-05
12                        -0.000075      -0.000006      -1.148867e-04
13                        -0.000050      -0.000087      -4.566016e-05
14                         0.000081       0.000166      -6.474664e-05
15                         0.000104      -0.000057      -9.179449e-05
16                        -0.000007       0.000060       4.328906e-05
17                         0.000065      -0.000025       6.585322e-06
18                         0.000061       0.000115       8.733136e-07
19                         0.000046       0.000011      -3.648677e-05

[20 rows x 380 columns]

In [6]:
b = set(a.columns)
b = list(b)
print(b)

['p-acetoxybenzoic', 'o-methylacetophenone', 'm-dimethoxybenzene', 'm-nitrotoluene', 'p-trans-anethole', 'o-aminobenzylamine', 'p-cyanobenzaldehyde', 'p-allylphenoxide', 'p-bromobenzoic acid', 'm-acetoxybenzoic', 'm-aminoacetophenone', 'p-hydroxybenzamide', 'm-hydroxybenzonitrile', 'm-methoxybenzaldehyde', 'm-toluoyl chloride', 'o-salicylic acid', 'p-(trifluoromethyl)acetophenone', 'o-aspirin', 'p-iodophenol', 'p-cyanophenol', 'm-bromobenzaldehyde', 'o-chlorobenzaldehyde', 'o-fluorophenol', 'p-xylene', 'p-fluoroaniline', 'p-acetaminophen', 'm-tolualdehyde', 'm-anisaldehyde', 'm-toluenesulfonyl chloride', 'p-chlorobenzaldehyde', 'p-hydroxybenzaldehyde', 'p-fluoroacetophenone', 'o-anthranilicacid', 'o-aminobenzylalcohol', 'm-toluicacid', 'o-dichlorobenzene', 'o-fluorobenzaldehyde', 'm-diethoxybenzene', 'o-bromotoluene', 'p-bromobenzaldehyde', 'p-bromotoluene', 'p-aminobenzoic', 'p-toluidine', 'm-diacetylbenzene', 'o-guaiacol', 'p-dimethoxybenzene', 'o-hydroxybenzonitrile', 'm-diacetoxybenzene', 'p-xylylenediamine', 'p-(trifluoromethyl)benzaldehyde', 'p-toluenesulfonyl chloride', 'o-1-chloro-2-nitrobenzene', 'm-fluorophenol', 'p-chloroaniline', 'm-chloroperbenzoicacid', 'p-acetamidophenol', 'o-ethoxyphenol', 'p-tolualdehyde', 'p-aminophenol', 'm-nitroacetophenone', 'o-hydroxyacetophenone', 'p-nitroacetophenone', 'p-hydroxybenzoic acid', 'o-dicyanobenzene', 'm-methoxyphenol', 'o-tolualdehyde', 'p-nitrotoluene', 'p-iodoanisole', 'o-salicylaldehyde', 'm-methyl o-toluate', 'o-toluidine', 'p-toluenesulfonamide', 'm-nitrophenol', 'p-bromoacetophenone', 'o-dihydroxybenzene', 'm-methyl o-aminobenzoate']

The library `sklearn.model_selection` has a function `train_test_split()`.
<br>
<br>`train_test_split` takes in a list, and splits it into two - a training dataset and a test dataset. By default the splitting size is 75:25 training:test, but this can be altered by passing a different value of the test_size parameter (`test_size=x`, where `x` is a value between 0 and 1 for 0% of the full dataset to 100% making up the test dataset).
<br>
<br>`train_samples, test_samples = sklearn.model_selection.train_test_split(samples,test_size=x)`
<br>
<br>**Note:** Each time `train_test_split()` is employed it will return a different distribution of data between the two subsets.

In [18]:
import sklearn.model_selection
train_samples, test_samples = sklearn.model_selection.train_test_split(b, test_size = 0.33)

In [19]:
training = a[train_samples]
testing = a[test_samples]
print(training)
print(testing)

       m-diethoxybenzene  m-diethoxybenzene  m-diethoxybenzene  \
630.0           0.000291           0.000290           0.000290
631.0           0.000291           0.000292           0.000290
632.0           0.000291           0.000290           0.000291
633.0           0.000291           0.000292           0.000290
634.0           0.000292           0.000291           0.000291
...                  ...                ...                ...
876.0           0.000287           0.000283           0.000286
877.0           0.000287           0.000285           0.000285
878.0           0.000288           0.000286           0.000288
879.0           0.000288           0.000290           0.000288
880.0           0.000288           0.000289           0.000287

       m-diethoxybenzene  m-diethoxybenzene  p-hydroxybenzamide  \
630.0           0.000290           0.000290            0.000201
631.0           0.000289           0.000292            0.000199
632.0           0.000290           0.000290            0.000200
633.0           0.000290           0.000292            0.000202
634.0           0.000290           0.000291            0.000201
...                  ...                ...                 ...
876.0           0.000284           0.000286            0.000254
877.0           0.000287           0.000286            0.000257
878.0           0.000286           0.000286            0.000255
879.0           0.000287           0.000287            0.000256
880.0           0.000288           0.000289            0.000256

       p-hydroxybenzamide  p-hydroxybenzamide  p-hydroxybenzamide  \
630.0            0.000150            0.000187            0.000194
631.0            0.000152            0.000188            0.000196
632.0            0.000152            0.000188            0.000199
633.0            0.000153            0.000191            0.000198
634.0            0.000154            0.000190            0.000199
...                   ...                 ...                 ...
876.0            0.000241            0.000254            0.000264
877.0            0.000242            0.000255            0.000263
878.0            0.000242            0.000254            0.000263
879.0            0.000241            0.000253            0.000264
880.0            0.000243            0.000254            0.000263

       p-hydroxybenzamide  ...  m-methyl o-toluate  m-methyl o-toluate  \
630.0            0.000151  ...            0.000298            0.000300
631.0            0.000151  ...            0.000299            0.000300
632.0            0.000151  ...            0.000298            0.000300
633.0            0.000152  ...            0.000299            0.000300
634.0            0.000153  ...            0.000299            0.000301
...                   ...  ...                 ...                 ...
876.0            0.000235  ...            0.000292            0.000296
877.0            0.000235  ...            0.000296            0.000294
878.0            0.000236  ...            0.000296            0.000296
879.0            0.000233  ...            0.000297            0.000295
880.0            0.000236  ...            0.000296            0.000295

       m-methyl o-toluate  m-methyl o-toluate  m-methyl o-toluate  \
630.0            0.000299            0.000299            0.000300
631.0            0.000298            0.000300            0.000299
632.0            0.000300            0.000299            0.000302
633.0            0.000299            0.000299            0.000299
634.0            0.000296            0.000299            0.000299
...                   ...                 ...                 ...
876.0            0.000292            0.000294            0.000295
877.0            0.000294            0.000294            0.000296
878.0            0.000293            0.000295            0.000296
879.0            0.000295            0.000297            0.000298
880.0            0.000297            0.000296            0.000297

       p-aminophenol  p-aminophenol  p-aminophenol  p-aminophenol  \
630.0       0.000215       0.000253       0.000227       0.000267
631.0       0.000213       0.000252       0.000228       0.000268
632.0       0.000213       0.000253       0.000228       0.000266
633.0       0.000215       0.000252       0.000228       0.000268
634.0       0.000214       0.000250       0.000227       0.000267
...              ...            ...            ...            ...
876.0       0.000188       0.000228       0.000191       0.000257
877.0       0.000187       0.000228       0.000188       0.000260
878.0       0.000186       0.000229       0.000188       0.000257
879.0       0.000185       0.000228       0.000186       0.000258
880.0       0.000187       0.000227       0.000185       0.000256

       p-aminophenol
630.0       0.000246
631.0       0.000245
632.0       0.000246
633.0       0.000246
634.0       0.000247
...              ...
876.0       0.000230
877.0       0.000228
878.0       0.000230
879.0       0.000228
880.0       0.000230

[251 rows x 250 columns]
       o-fluorobenzaldehyde  o-fluorobenzaldehyde  o-fluorobenzaldehyde  \
630.0              0.000114              0.000115              0.000114
631.0              0.000118              0.000117              0.000118
632.0              0.000134              0.000135              0.000135
633.0              0.000161              0.000160              0.000162
634.0              0.000184              0.000184              0.000185
...                     ...                   ...                   ...
876.0              0.000216              0.000216              0.000216
877.0              0.000242              0.000241              0.000239
878.0              0.000263              0.000263              0.000263
879.0              0.000277              0.000276              0.000276
880.0              0.000282              0.000283              0.000280

       o-fluorobenzaldehyde  o-fluorobenzaldehyde  m-dimethoxybenzene  \
630.0              0.000114              0.000114            0.000291
631.0              0.000117              0.000118            0.000290
632.0              0.000135              0.000135            0.000290
633.0              0.000161              0.000158            0.000290
634.0              0.000184              0.000184            0.000291
...                     ...                   ...                 ...
876.0              0.000214              0.000215            0.000287
877.0              0.000240              0.000242            0.000288
878.0              0.000264              0.000262            0.000286
879.0              0.000275              0.000273            0.000287
880.0              0.000278              0.000280            0.000287

       m-dimethoxybenzene  m-dimethoxybenzene  m-dimethoxybenzene  \
630.0            0.000290            0.000291            0.000291
631.0            0.000290            0.000291            0.000290
632.0            0.000291            0.000289            0.000291
633.0            0.000292            0.000289            0.000293
634.0            0.000289            0.000292            0.000289
...                   ...                 ...                 ...
876.0            0.000287            0.000286            0.000285
877.0            0.000287            0.000286            0.000287
878.0            0.000286            0.000287            0.000288
879.0            0.000286            0.000286            0.000286
880.0            0.000287            0.000287            0.000288

       m-dimethoxybenzene  ...  p-(trifluoromethyl)acetophenone  \
630.0            0.000292  ...                         0.000281
631.0            0.000289  ...                         0.000276
632.0            0.000291  ...                         0.000272
633.0            0.000291  ...                         0.000281
634.0            0.000289  ...                         0.000285
...                   ...  ...                              ...
876.0            0.000286  ...                         0.000276
877.0            0.000286  ...                         0.000275
878.0            0.000287  ...                         0.000274
879.0            0.000287  ...                         0.000275
880.0            0.000287  ...                         0.000275

       p-(trifluoromethyl)acetophenone  p-(trifluoromethyl)acetophenone  \
630.0                         0.000282                         0.000284
631.0                         0.000279                         0.000281
632.0                         0.000275                         0.000276
633.0                         0.000283                         0.000286
634.0                         0.000286                         0.000289
...                                ...                              ...
876.0                         0.000276                         0.000282
877.0                         0.000277                         0.000282
878.0                         0.000276                         0.000280
879.0                         0.000275                         0.000282
880.0                         0.000277                         0.000282

       p-(trifluoromethyl)acetophenone  p-(trifluoromethyl)acetophenone  \
630.0                         0.000281                         0.000280
631.0                         0.000279                         0.000275
632.0                         0.000272                         0.000271
633.0                         0.000283                         0.000281
634.0                         0.000283                         0.000284
...                                ...                              ...
876.0                         0.000278                         0.000273
877.0                         0.000278                         0.000273
878.0                         0.000279                         0.000273
879.0                         0.000278                         0.000273
880.0                         0.000278                         0.000274

       m-methoxybenzaldehyde  m-methoxybenzaldehyde  m-methoxybenzaldehyde  \
630.0               0.000263               0.000265               0.000264
631.0               0.000263               0.000265               0.000265
632.0               0.000260               0.000260               0.000260
633.0               0.000257               0.000255               0.000257
634.0               0.000253               0.000251               0.000252
...                      ...                    ...                    ...
876.0               0.000234               0.000232               0.000234
877.0               0.000235               0.000237               0.000235
878.0               0.000235               0.000235               0.000236
879.0               0.000237               0.000236               0.000237
880.0               0.000238               0.000236               0.000237

       m-methoxybenzaldehyde  m-methoxybenzaldehyde
630.0               0.000265               0.000266
631.0               0.000263               0.000264
632.0               0.000259               0.000261
633.0               0.000256               0.000257
634.0               0.000254               0.000252
...                      ...                    ...
876.0               0.000236               0.000236
877.0               0.000236               0.000235
878.0               0.000235               0.000234
879.0               0.000236               0.000236
880.0               0.000235               0.000236

[251 rows x 130 columns]

In [20]:
train_labels = []
test_labels = []
for i in training.columns:
    train_labels.append(i[0])
for i in testing.columns:
    test_labels.append(i[0])
print(train_labels)
print(test_labels)

['m', 'm', 'm', 'm', 'm', 'p', 'p', 'p', 'p', 'p', 'm', 'm', 'm', 'm', 'm', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'm', 'm', 'm', 'm', 'm', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'm', 'm', 'm', 'm', 'm', 'm', 'm', 'm', 'm', 'm', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'm', 'm', 'm', 'm', 'm', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'm', 'm', 'm', 'm', 'm', 'p', 'p', 'p', 'p', 'p', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'm', 'm', 'm', 'm', 'm', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'm', 'm', 'm', 'm', 'm', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'o', 'o', 'o', 'o', 'o', 'm', 'm', 'm', 'm', 'm', 'o', 'o', 'o', 'o', 'o', 'p', 'p', 'p', 'p', 'p', 'm', 'm', 'm', 'm', 'm', 'o', 'o', 'o', 'o', 'o', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'o', 'o', 'o', 'o', 'o', 'p', 'p', 'p', 'p', 'p', 'o', 'o', 'o', 'o', 'o', 'm', 'm', 'm', 'm', 'm', 'p', 'p', 'p', 'p', 'p']
['o', 'o', 'o', 'o', 'o', 'm', 'm', 'm', 'm', 'm', 'm', 'm', 'm', 'm', 'm', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'o', 'o', 'o', 'o', 'o', 'p', 'p', 'p', 'p', 'p', 'o', 'o', 'o', 'o', 'o', 'p', 'p', 'p', 'p', 'p', 'o', 'o', 'o', 'o', 'o', 'p', 'p', 'p', 'p', 'p', 'o', 'o', 'o', 'o', 'o', 'm', 'm', 'm', 'm', 'm', 'm', 'm', 'm', 'm', 'm', 'm', 'm', 'm', 'm', 'm', 'p', 'p', 'p', 'p', 'p', 'm', 'm', 'm', 'm', 'm', 'm', 'm', 'm', 'm', 'm', 'm', 'm', 'm', 'm', 'm', 'o', 'o', 'o', 'o', 'o', 'm', 'm', 'm', 'm', 'm', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'm', 'm', 'm', 'm', 'm']

---

### The k-Nearest Neighbours Algorithm

With an appropriately prepared dataset separated into training and testing subsets, it is now possible to pass the data to a machine learning algorithm. In this case you will employ the k-nearest neighbours algorithm, which categorises data based on distance in dataspace.
<br>
<br>We will employ the `sklearn.neighbors` library to carry out the machine learning.

In [21]:
import sklearn.neighbors

The `sklearn.neighbors` library lets you create an object called a `KNeighborsClassifier()`, which takes as an argument the number of nearest neighbours to use. (You might draw parallels between this and the `PCA` object generated in the previous notebook.)

In [22]:
knn = sklearn.neighbors.KNeighborsClassifier(n_neighbors=3)

The `KNeighborsClassifier` object has a method called `fit(training data, training labels)`, which sets up/trains your model, ready to make predictions. Much like with PCA, the `sklearn` library expects your data with samples as rows, and features as columns (as you encountered with PCA). Recall that a DataFrame has an attribute which could help here.

In [23]:
knn.fit(training.T, train_labels)

KNeighborsClassifier(n_neighbors=3)

You have now made a KNearestNeighbours object, and trained it with your processed data.

The `score(testing data, testing labels)` method can be used to test a trained `KNeighborsClassifier` object with testing data. It returns a score of what percentage of test data your model correctly classifies.

**Note:** Again, the testing data must be handed to the method with samples as rows and features as columns.

In [24]:
score = knn.score(testing.T, test_labels)
print(score)

0.7461538461538462

You will likely get a value between 60% and 90%. The variability is caused by different possible test/train splits - if you train your model with a different subset of the data, it will perform differently.

In [41]:
def knn(df, test_size=0.33, n_neighbors=3):
    compounds = list(set(df.columns))
    train_samples, test_samples = sklearn.model_selection.train_test_split(
        compounds, test_size=test_size)
    training = df[train_samples]
    testing = df[test_samples]
    train_labels = [i[0] for i in training.columns] # much more concise than define list -> for loop -> append
    test_labels = [i[0] for i in testing.columns]
    knn = sklearn.neighbors.KNeighborsClassifier(n_neighbors=n_neighbors)
    knn.fit(training.T, train_labels)
    score = knn.score(testing.T, test_labels)
    # print(score)
    return score

print(score)

0.7461538461538462

To get a better idea of the accuracy of the model, it is better to average the score over a few hundred different test train splits (recall that each time you use `train_test_split()` it generates a new split).

In [42]:
import numpy as np

scores = []
for i in range(500):
    scores.append(knn(a))

mean_score = np.round(np.mean(scores), 4)
std_error = np.round(np.std(scores) / np.sqrt(len(scores)), 4)
print(f"Mean score: {mean_score}")
print(f"Standard error: {std_error}")

Mean score: 0.7422
Standard error: 0.0033

Once a `KNeighborsClassifier` object has been trained, it is also possible to employ the `predict()` method to attempt to assign a particular subset of data from your test subset.

In [38]:
print(testing.columns)

Index(['o-fluorobenzaldehyde', 'o-fluorobenzaldehyde', 'o-fluorobenzaldehyde',
       'o-fluorobenzaldehyde', 'o-fluorobenzaldehyde', 'm-dimethoxybenzene',
       'm-dimethoxybenzene', 'm-dimethoxybenzene', 'm-dimethoxybenzene',
       'm-dimethoxybenzene',
       ...
       'p-(trifluoromethyl)acetophenone', 'p-(trifluoromethyl)acetophenone',
       'p-(trifluoromethyl)acetophenone', 'p-(trifluoromethyl)acetophenone',
       'p-(trifluoromethyl)acetophenone', 'm-methoxybenzaldehyde',
       'm-methoxybenzaldehyde', 'm-methoxybenzaldehyde',
       'm-methoxybenzaldehyde', 'm-methoxybenzaldehyde'],
      dtype='object', length=130)

In [44]:
knn_model = sklearn.neighbors.KNeighborsClassifier(n_neighbors=3)
knn_model.fit(training.T, train_labels)

# Then predict:
predictions = knn_model.predict(testing['o-fluorobenzaldehyde'].T)
print("o-fluorobenzaldehyde predictions:", predictions)

predictions2 = knn_model.predict(testing['m-dimethoxybenzene'].T)
print("m-dimethoxybenzene predictions:", predictions2)

o-fluorobenzaldehyde predictions: ['o' 'o' 'o' 'o' 'o']
m-dimethoxybenzene predictions: ['m' 'm' 'm' 'm' 'm']

---